def get_dropdown_list_search():
    dropdown_list = [{'label': 'A General Theory Of Employment, Interest, And Money',
  'value': 'A General Theory Of Employment, Interest, And Money'},
 {'label': 'A Treatise Concerning The Principles Of Human Knowledge',
  'value': 'A Treatise Concerning The Principles Of Human Knowledge'},
 {'label': 'A Treatise Of Human Nature',
  'value': 'A Treatise Of Human Nature'},
 {'label': 'Analytic', 'value': 'Analytic'},
 {'label': 'Anti-Oedipus', 'value': 'Anti-Oedipus'},
 {'label': 'Aristotle', 'value': 'Aristotle'},
 {'label': 'Aristotle - Complete Works',
  'value': 'Aristotle - Complete Works'},
 {'label': 'Being And Time', 'value': 'Being And Time'},
 {'label': 'Berkeley', 'value': 'Berkeley'},
 {'label': 'Capital', 'value': 'Capital'},
 {'label': 'Capitalism', 'value': 'Capitalism'},
 {'label': 'Communism', 'value': 'Communism'},
 {'label': 'Continental', 'value': 'Continental'},
 {'label': 'Critique Of Judgement', 'value': 'Critique Of Judgement'},
 {'label': 'Critique Of Practical Reason',
  'value': 'Critique Of Practical Reason'},
 {'label': 'Critique Of Pure Reason', 'value': 'Critique Of Pure Reason'},
 {'label': 'Deleuze', 'value': 'Deleuze'},
 {'label': 'Derrida', 'value': 'Derrida'},
 {'label': 'Descartes', 'value': 'Descartes'},
 {'label': 'Dialogues Concerning Natural Religion',
  'value': 'Dialogues Concerning Natural Religion'},
 {'label': 'Difference And Repetition', 'value': 'Difference And Repetition'},
 {'label': 'Discourse On Method', 'value': 'Discourse On Method'},
 {'label': 'Elements Of The Philosophy Of Right',
  'value': 'Elements Of The Philosophy Of Right'},
 {'label': 'Empiricism', 'value': 'Empiricism'},
 {'label': 'Enchiridion', 'value': 'Enchiridion'},
 {'label': 'Epictetus', 'value': 'Epictetus'},
 {'label': 'Essay Concerning Human Understanding',
  'value': 'Essay Concerning Human Understanding'},
 {'label': 'Essential Works Of Lenin', 'value': 'Essential Works Of Lenin'},
 {'label': 'Ethics', 'value': 'Ethics'},
 {'label': 'Fichte', 'value': 'Fichte'},
 {'label': 'Foucault', 'value': 'Foucault'},
 {'label': 'German Idealism', 'value': 'German Idealism'},
 {'label': 'Hegel', 'value': 'Hegel'},
 {'label': 'Heidegger', 'value': 'Heidegger'},
 {'label': 'Hume', 'value': 'Hume'},
 {'label': 'Husserl', 'value': 'Husserl'},
 {'label': 'Kant', 'value': 'Kant'},
 {'label': 'Keynes', 'value': 'Keynes'},
 {'label': 'Kripke', 'value': 'Kripke'},
 {'label': 'Leibniz', 'value': 'Leibniz'},
 {'label': 'Lenin', 'value': 'Lenin'},
 {'label': 'Lewis', 'value': 'Lewis'},
 {'label': 'Lewis - Papers', 'value': 'Lewis - Papers'},
 {'label': 'Locke', 'value': 'Locke'},
 {'label': 'Madness And Civilization', 'value': 'Madness And Civilization'},
 {'label': 'Malebranche', 'value': 'Malebranche'},
 {'label': 'Marcus Aurelius', 'value': 'Marcus Aurelius'},
 {'label': 'Marx', 'value': 'Marx'},
 {'label': 'Meditations', 'value': 'Meditations'},
 {'label': 'Meditations On First Philosophy',
  'value': 'Meditations On First Philosophy'},
 {'label': 'Merleau-Ponty', 'value': 'Merleau-Ponty'},
 {'label': 'Moore', 'value': 'Moore'},
 {'label': 'Naming And Necessity', 'value': 'Naming And Necessity'},
 {'label': 'Off The Beaten Track', 'value': 'Off The Beaten Track'},
 {'label': 'On The Improvement Of Understanding',
  'value': 'On The Improvement Of Understanding'},
 {'label': 'On The Principles Of Political Economy And Taxation',
  'value': 'On The Principles Of Political Economy And Taxation'},
 {'label': 'Phenomenology', 'value': 'Phenomenology'},
 {'label': 'Philosophical Investigations',
  'value': 'Philosophical Investigations'},
 {'label': 'Philosophical Studies', 'value': 'Philosophical Studies'},
 {'label': 'Philosophical Troubles', 'value': 'Philosophical Troubles'},
 {'label': 'Plato', 'value': 'Plato'},
 {'label': 'Plato - Complete Works', 'value': 'Plato - Complete Works'},
 {'label': 'Popper', 'value': 'Popper'},
 {'label': 'Quine', 'value': 'Quine'},
 {'label': 'Quintessence', 'value': 'Quintessence'},
 {'label': 'Rationalism', 'value': 'Rationalism'},
 {'label': 'Ricardo', 'value': 'Ricardo'},
 {'label': 'Russell', 'value': 'Russell'},
 {'label': 'Science Of Logic', 'value': 'Science Of Logic'},
 {'label': 'Second Treatise On Government',
  'value': 'Second Treatise On Government'},
 {'label': 'Smith', 'value': 'Smith'},
 {'label': 'Spinoza', 'value': 'Spinoza'},
 {'label': 'Stoicism', 'value': 'Stoicism'},
 {'label': 'The Analysis Of Mind', 'value': 'The Analysis Of Mind'},
 {'label': 'The Birth Of The Clinic', 'value': 'The Birth Of The Clinic'},
 {'label': 'The Communist Manifesto', 'value': 'The Communist Manifesto'},
 {'label': 'The Crisis Of The European Sciences And Phenomenology',
  'value': 'The Crisis Of The European Sciences And Phenomenology'},
 {'label': 'The Idea Of Phenomenology', 'value': 'The Idea Of Phenomenology'},
 {'label': 'The Logic Of Scientific Discovery',
  'value': 'The Logic Of Scientific Discovery'},
 {'label': 'The Order Of Things', 'value': 'The Order Of Things'},
 {'label': 'The Phenomenology Of Perception',
  'value': 'The Phenomenology Of Perception'},
 {'label': 'The Phenomenology Of Spirit',
  'value': 'The Phenomenology Of Spirit'},
 {'label': 'The Problems Of Philosophy',
  'value': 'The Problems Of Philosophy'},
 {'label': 'The Search After Truth', 'value': 'The Search After Truth'},
 {'label': 'The System Of Ethics', 'value': 'The System Of Ethics'},
 {'label': 'The Wealth Of Nations', 'value': 'The Wealth Of Nations'},
 {'label': 'Theodicy', 'value': 'Theodicy'},
 {'label': 'Three Dialogues', 'value': 'Three Dialogues'},
 {'label': 'Tractatus Logico-Philosophicus',
  'value': 'Tractatus Logico-Philosophicus'},
 {'label': 'Wittgenstein', 'value': 'Wittgenstein'},
 {'label': 'Writing And Difference', 'value': 'Writing And Difference'}]
    return dropdown_list