def get_dropdown_list_search():
    dropdown_list = [{'label': 'A General Theory Of Employment, Interest, And Money',
  'value': 'A General Theory Of Employment, Interest, And Money'},
 {'label': 'A Treatise Concerning The Principles Of Human Knowledge',
  'value': 'A Treatise Concerning The Principles Of Human Knowledge'},
 {'label': 'A Treatise Of Human Nature',
  'value': 'A Treatise Of Human Nature'},
 {'label': 'Analytic', 'value': 'Analytic'},
 {'label': 'Anselm', 'value': 'Anselm'},
 {'label': 'Anti-Oedipus', 'value': 'Anti-Oedipus'},
 {'label': 'Aristotle', 'value': 'Aristotle'},
 {'label': 'Aristotle - Complete Works',
  'value': 'Aristotle - Complete Works'},
 {'label': 'Augustine', 'value': 'Augustine'},
 {'label': 'Beauvoir', 'value': 'Beauvoir'},
 {'label': 'Being And Time', 'value': 'Being And Time'},
 {'label': 'Being and Nothingness', 'value': 'Being and Nothingness'},
 {'label': 'Berkeley', 'value': 'Berkeley'},
 {'label': 'Beyond Good And Evil', 'value': 'Beyond Good And Evil'},
 {'label': 'Capital', 'value': 'Capital'},
 {'label': 'Capitalism', 'value': 'Capitalism'},
 {'label': 'Communism', 'value': 'Communism'},
 {'label': 'Confessions', 'value': 'Confessions'},
 {'label': 'Continental', 'value': 'Continental'},
 {'label': 'Critique Of Judgement', 'value': 'Critique Of Judgement'},
 {'label': 'Critique Of Practical Reason',
  'value': 'Critique Of Practical Reason'},
 {'label': 'Critique Of Pure Reason', 'value': 'Critique Of Pure Reason'},
 {'label': 'Daoism', 'value': 'Daoism'},
 {'label': 'Davis', 'value': 'Davis'},
 {'label': 'De Veritate', 'value': 'De Veritate'},
 {'label': 'Deleuze', 'value': 'Deleuze'},
 {'label': 'Derrida', 'value': 'Derrida'},
 {'label': 'Descartes', 'value': 'Descartes'},
 {'label': 'Dialogues Concerning Natural Religion',
  'value': 'Dialogues Concerning Natural Religion'},
 {'label': 'Difference And Repetition', 'value': 'Difference And Repetition'},
 {'label': 'Discourse On Method', 'value': 'Discourse On Method'},
 {'label': 'Ecce Homo', 'value': 'Ecce Homo'},
 {'label': 'Elements Of The Philosophy Of Right',
  'value': 'Elements Of The Philosophy Of Right'},
 {'label': 'Empiricism', 'value': 'Empiricism'},
 {'label': 'Enchiridion', 'value': 'Enchiridion'},
 {'label': 'Epictetus', 'value': 'Epictetus'},
 {'label': 'Essay Concerning Human Understanding',
  'value': 'Essay Concerning Human Understanding'},
 {'label': 'Essential Works Of Lenin', 'value': 'Essential Works Of Lenin'},
 {'label': 'Ethics', 'value': 'Ethics'},
 {'label': 'Existentialism', 'value': 'Existentialism'},
 {'label': 'Fear and Trembling', 'value': 'Fear and Trembling'},
 {'label': 'Feminism', 'value': 'Feminism'},
 {'label': 'Fichte', 'value': 'Fichte'},
 {'label': 'Foucault', 'value': 'Foucault'},
 {'label': 'German Idealism', 'value': 'German Idealism'},
 {'label': 'Hegel', 'value': 'Hegel'},
 {'label': 'Heidegger', 'value': 'Heidegger'},
 {'label': 'History Of Madness', 'value': 'History Of Madness'},
 {'label': 'Hobbes', 'value': 'Hobbes'},
 {'label': 'Hume', 'value': 'Hume'},
 {'label': 'Husserl', 'value': 'Husserl'},
 {'label': 'Kant', 'value': 'Kant'},
 {'label': 'Keynes', 'value': 'Keynes'},
 {'label': 'Kierkegaard', 'value': 'Kierkegaard'},
 {'label': 'Kripke', 'value': 'Kripke'},
 {'label': 'Leibniz', 'value': 'Leibniz'},
 {'label': 'Lenin', 'value': 'Lenin'},
 {'label': 'Leviathan', 'value': 'Leviathan'},
 {'label': 'Lewis', 'value': 'Lewis'},
 {'label': 'Lewis - Papers', 'value': 'Lewis - Papers'},
 {'label': 'Locke', 'value': 'Locke'},
 {'label': 'Malebranche', 'value': 'Malebranche'},
 {'label': 'Marcus Aurelius', 'value': 'Marcus Aurelius'},
 {'label': 'Marx', 'value': 'Marx'},
 {'label': 'Meditations', 'value': 'Meditations'},
 {'label': 'Meditations On First Philosophy',
  'value': 'Meditations On First Philosophy'},
 {'label': 'Merleau-Ponty', 'value': 'Merleau-Ponty'},
 {'label': 'Moore', 'value': 'Moore'},
 {'label': 'Naming And Necessity', 'value': 'Naming And Necessity'},
 {'label': 'Nietzsche', 'value': 'Nietzsche'},
 {'label': 'Off The Beaten Track', 'value': 'Off The Beaten Track'},
 {'label': 'On Anger', 'value': 'On Anger'},
 {'label': 'On Benefits', 'value': 'On Benefits'},
 {'label': 'On Certainty', 'value': 'On Certainty'},
 {'label': 'On Clemency', 'value': 'On Clemency'},
 {'label': 'On The Improvement Of Understanding',
  'value': 'On The Improvement Of Understanding'},
 {'label': 'On The Principles Of Political Economy And Taxation',
  'value': 'On The Principles Of Political Economy And Taxation'},
 {'label': 'Phenomenology', 'value': 'Phenomenology'},
 {'label': 'Philosophical Investigations',
  'value': 'Philosophical Investigations'},
 {'label': 'Philosophical Studies', 'value': 'Philosophical Studies'},
 {'label': 'Philosophical Troubles', 'value': 'Philosophical Troubles'},
 {'label': 'Plato', 'value': 'Plato'},
 {'label': 'Plato - Complete Works', 'value': 'Plato - Complete Works'},
 {'label': 'Popper', 'value': 'Popper'},
 {'label': 'Proslogion', 'value': 'Proslogion'},
 {'label': 'Quine', 'value': 'Quine'},
 {'label': 'Quintessence', 'value': 'Quintessence'},
 {'label': 'Rationalism', 'value': 'Rationalism'},
 {'label': 'Ricardo', 'value': 'Ricardo'},
 {'label': 'Russell', 'value': 'Russell'},
 {'label': 'Sartre', 'value': 'Sartre'},
 {'label': 'Scholasticism', 'value': 'Scholasticism'},
 {'label': 'Science Of Logic', 'value': 'Science Of Logic'},
 {'label': 'Second Treatise On Government',
  'value': 'Second Treatise On Government'},
 {'label': 'Seneca', 'value': 'Seneca'},
 {'label': 'Smith', 'value': 'Smith'},
 {'label': 'Spinoza', 'value': 'Spinoza'},
 {'label': 'Stoicism', 'value': 'Stoicism'},
 {'label': 'The Analysis Of Mind', 'value': 'The Analysis Of Mind'},
 {'label': 'The Antichrist', 'value': 'The Antichrist'},
 {'label': 'The Birth Of The Clinic', 'value': 'The Birth Of The Clinic'},
 {'label': 'The Book of Zhuangzi ', 'value': 'The Book of Zhuangzi '},
 {'label': 'The Communist Manifesto', 'value': 'The Communist Manifesto'},
 {'label': 'The Crisis Of The European Sciences And Phenomenology',
  'value': 'The Crisis Of The European Sciences And Phenomenology'},
 {'label': 'The Idea Of Phenomenology', 'value': 'The Idea Of Phenomenology'},
 {'label': 'The Logic Of Scientific Discovery',
  'value': 'The Logic Of Scientific Discovery'},
 {'label': 'The Order Of Things', 'value': 'The Order Of Things'},
 {'label': 'The Phenomenology Of Perception',
  'value': 'The Phenomenology Of Perception'},
 {'label': 'The Phenomenology Of Spirit',
  'value': 'The Phenomenology Of Spirit'},
 {'label': 'The Problems Of Philosophy',
  'value': 'The Problems Of Philosophy'},
 {'label': 'The Search After Truth', 'value': 'The Search After Truth'},
 {'label': 'The Second Sex', 'value': 'The Second Sex'},
 {'label': 'The System Of Ethics', 'value': 'The System Of Ethics'},
 {'label': 'The Wealth Of Nations', 'value': 'The Wealth Of Nations'},
 {'label': 'Theodicy', 'value': 'Theodicy'},
 {'label': 'Three Dialogues', 'value': 'Three Dialogues'},
 {'label': 'Thus Spake Zarathustra', 'value': 'Thus Spake Zarathustra'},
 {'label': 'Tractatus Logico-Philosophicus',
  'value': 'Tractatus Logico-Philosophicus'},
 {'label': 'Twilight Of The Idols', 'value': 'Twilight Of The Idols'},
 {'label': 'Vindication Of The Rights Of Woman',
  'value': 'Vindication Of The Rights Of Woman'},
 {'label': 'Wittgenstein', 'value': 'Wittgenstein'},
 {'label': 'Wollstonecraft', 'value': 'Wollstonecraft'},
 {'label': 'Women, Race, And Class', 'value': 'Women, Race, And Class'},
 {'label': 'Writing And Difference', 'value': 'Writing And Difference'},
 {'label': 'Zhuangzi', 'value': 'Zhuangzi'}]
    return dropdown_list

def get_classifier_dict():
  classifier_dict = {'Plato': 'SCHOOL',
 'Aristotle': 'SCHOOL',
 'Locke': 'AUTHOR',
 'Hume': 'AUTHOR',
 'Berkeley': 'AUTHOR',
 'Spinoza': 'AUTHOR',
 'Leibniz': 'AUTHOR',
 'Descartes': 'AUTHOR',
 'Malebranche': 'AUTHOR',
 'Russell': 'AUTHOR',
 'Moore': 'AUTHOR',
 'Wittgenstein': 'AUTHOR',
 'Lewis': 'AUTHOR',
 'Quine': 'AUTHOR',
 'Popper': 'AUTHOR',
 'Kripke': 'AUTHOR',
 'Foucault': 'AUTHOR',
 'Derrida': 'AUTHOR',
 'Deleuze': 'AUTHOR',
 'Merleau-Ponty': 'AUTHOR',
 'Husserl': 'AUTHOR',
 'Heidegger': 'AUTHOR',
 'Kant': 'AUTHOR',
 'Fichte': 'AUTHOR',
 'Hegel': 'AUTHOR',
 'Marx': 'AUTHOR',
 'Lenin': 'AUTHOR',
 'Smith': 'AUTHOR',
 'Ricardo': 'AUTHOR',
 'Keynes': 'AUTHOR',
 'Epictetus': 'AUTHOR',
 'Marcus Aurelius': 'AUTHOR',
 'Nietzsche': 'SCHOOL',
 'Wollstonecraft': 'AUTHOR',
 'Beauvoir': 'AUTHOR',
 'Davis': 'AUTHOR',
 'Augustine': 'AUTHOR',
 'Anselm': 'AUTHOR',
 'Seneca': 'AUTHOR',
 'Kierkegaard': 'SCHOOL',
 'Hobbes': 'SCHOOL',
 'Sartre': 'AUTHOR',
 'Zhuangzi': 'AUTHOR',
 'Plato - Complete Works': 'TITLE',
 'Aristotle - Complete Works': 'TITLE',
 'Second Treatise On Government': 'TITLE',
 'Essay Concerning Human Understanding': 'TITLE',
 'A Treatise Of Human Nature': 'TITLE',
 'Dialogues Concerning Natural Religion': 'TITLE',
 'Three Dialogues': 'TITLE',
 'A Treatise Concerning The Principles Of Human Knowledge': 'TITLE',
 'Ethics': 'TITLE',
 'On The Improvement Of Understanding': 'TITLE',
 'Theodicy': 'TITLE',
 'Discourse On Method': 'TITLE',
 'Meditations On First Philosophy': 'TITLE',
 'The Search After Truth': 'TITLE',
 'The Analysis Of Mind': 'TITLE',
 'The Problems Of Philosophy': 'TITLE',
 'Philosophical Studies': 'TITLE',
 'Philosophical Investigations': 'TITLE',
 'Tractatus Logico-Philosophicus': 'TITLE',
 'Lewis - Papers': 'TITLE',
 'Quintessence': 'TITLE',
 'The Logic Of Scientific Discovery': 'TITLE',
 'Naming And Necessity': 'TITLE',
 'Philosophical Troubles': 'TITLE',
 'On Certainty': 'TITLE',
 'The Birth Of The Clinic': 'TITLE',
 'History Of Madness': 'TITLE',
 'The Order Of Things': 'TITLE',
 'Writing And Difference': 'TITLE',
 'Difference And Repetition': 'TITLE',
 'Anti-Oedipus': 'TITLE',
 'The Phenomenology Of Perception': 'TITLE',
 'The Crisis Of The European Sciences And Phenomenology': 'TITLE',
 'The Idea Of Phenomenology': 'TITLE',
 'Being And Time': 'TITLE',
 'Off The Beaten Track': 'TITLE',
 'Critique Of Practical Reason': 'TITLE',
 'Critique Of Judgement': 'TITLE',
 'Critique Of Pure Reason': 'TITLE',
 'The System Of Ethics': 'TITLE',
 'Science Of Logic': 'TITLE',
 'The Phenomenology Of Spirit': 'TITLE',
 'Elements Of The Philosophy Of Right': 'TITLE',
 'Capital': 'TITLE',
 'The Communist Manifesto': 'TITLE',
 'Essential Works Of Lenin': 'TITLE',
 'The Wealth Of Nations': 'TITLE',
 'On The Principles Of Political Economy And Taxation': 'TITLE',
 'A General Theory Of Employment, Interest, And Money': 'TITLE',
 'Enchiridion': 'TITLE',
 'Meditations': 'TITLE',
 'The Antichrist': 'TITLE',
 'Beyond Good And Evil': 'TITLE',
 'Ecce Homo': 'TITLE',
 'Twilight Of The Idols': 'TITLE',
 'Thus Spake Zarathustra': 'TITLE',
 'Vindication Of The Rights Of Woman': 'TITLE',
 'The Second Sex': 'TITLE',
 'Women, Race, And Class': 'TITLE',
 'Confessions': 'TITLE',
 'Proslogion': 'TITLE',
 'De Veritate': 'TITLE',
 'On Benefits': 'TITLE',
 'On Anger': 'TITLE',
 'On Clemency': 'TITLE',
 'Fear and Trembling': 'TITLE',
 'Leviathan': 'TITLE',
 'Being and Nothingness': 'TITLE',
 'The Book of Zhuangzi ': 'TITLE',
 'Empiricism': 'SCHOOL',
 'Rationalism': 'SCHOOL',
 'Analytic': 'SCHOOL',
 'Continental': 'SCHOOL',
 'Phenomenology': 'SCHOOL',
 'German Idealism': 'SCHOOL',
 'Communism': 'SCHOOL',
 'Capitalism': 'SCHOOL',
 'Stoicism': 'SCHOOL',
 'Feminism': 'SCHOOL',
 'Scholasticism': 'SCHOOL',
 'Existentialism': 'SCHOOL',
 'Daoism': 'SCHOOL'}
  return classifier_dict